version: '3'

services:

  heosolddb:
    container_name: heosolddb
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: tcfPm)y_Io7nLt9c
      MYSQL_USER: admin
      MYSQL_PASSWORD: Szigony123$$
      MYSQL_DATABASE: heos
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    networks:
      vpcbr:
        ipv4_address: 172.29.0.2
        
  heosold-apache:
    container_name: heosold-apache
    # image: php:5.6-apache
    build: .
    depends_on:
      - heosolddb
    environment:
      - DEBUG=false
    volumes:
      - .:/var/www/html/
    ports:
      - 3030:80
      - 3031:443
    networks:
      vpcbr:
        ipv4_address: 172.29.0.3

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.29.0.0/16
         gateway: 172.29.0.1