version: '2.3.3'

services:

  heosdb:
    container_name: heosdb
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: tcfPm)y_Io7nLt9c
      MYSQL_USER: admin
      MYSQL_PASSWORD: Szigony123$$
      MYSQL_DATABASE: heos
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 172.26.0.2
        
  heosopencart-apache:
    container_name: heosopencart-apache
    image: sample:8.0-apache
    build: .
    depends_on:
      - heosdb
    environment:
      - DEBUG=false
    volumes:
      - ./heosopencart/upload:/var/www/html/
    ports:
      - 3030:80
      - 3031:443
    networks:
      vpcbr:
        ipv4_address: 172.26.0.3
        
# https://github.com/srinisrigo/heos.git
  heos-apache:
    container_name: heos-apache
    image: sample:8.0-apache
    build: .
    depends_on:
      - heosdb
    environment:
      - DEBUG=false
    volumes:
      - ./heos:/var/www/html/
    ports:
      - 4040:80
      - 4041:443
    networks:
      vpcbr:
        ipv4_address: 172.26.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.26.0.0/16
         gateway: 172.26.0.1

# Volumes
# volumes:
#   db_conf: